[cogs]

[cogs.admin]
enabled = true

[cogs.chatbot]
enabled = true
max_output_tokens = 8000
token_window_size = 16000
max_images_in_window = 2
model_temperature = 0.2
default_model = "claude-haiku-4-5"
default_chat_prompt = "data/prompts/default.yaml"
random_response_chance = 0.005
random_response_use_n_messages = 5
response_rate_limit = 3
rate_limit_interval = 5
enable_profiling = false
prefer_image_urls = false
enable_web_search = true

[cogs.markov]
enabled = true

[cogs.media_tracker]
enabled = true
update_interval = 5
letterboxd_channels = [237647756049514498, 710120383235227670]
backloggd_channels = [710120383235227670]

[cogs.reminders]
enabled = true

[cogs.scheduled_posts]
enabled = true

[cogs.spam]
enabled = true

[cogs.spelling]
enabled = true
custom_dictionary = "data/slash_dict.txt"

[cogs.spelling.servers."710120382144839691"]
users = [357550184655224833, 151378138612367360, 284782689226063874]
post_channel = 710120383235227670

[cogs.tools]
enabled = true

[cogs.users]
enabled = true

[cogs.videos]
enabled = true

[cogs.weather]
enabled = true

[cooldown]
rate = 3
standard = 60
no_cooldown_users = [151378138612367360]
no_cooldown_servers = [237647756049514498]

[discord]
max_chars = 1950
development_servers = [815237689775357992]

[files]
database = "data/slashbot.sqlite.db"
bad_words = "data/text/badwords.txt"
god_words = "data/text/godwords.txt"
scheduled_posts = "data/scheduled_posts.yaml"

[logging]
log_location = "logs/slashbot.log"

[markov]
enable_markov_training = false
enable_pregen_sentences = true
num_pregen_sentences = 5
pregenerate_limit = 2
