"""change column name from letterboxd_user to letterboxd_username

Revision ID: 10572a9c2c1c
Revises:
Create Date: 2025-09-13 18:24:59.945117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10572a9c2c1c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikifeet_pictures")
    op.drop_table("wikifeet_comments")
    op.drop_table("wikifeet_models")
    op.add_column("users", sa.Column("letterboxd_username", sa.String(length=64), nullable=True))
    op.drop_column("users", "letterboxd_user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("letterboxd_user", sa.VARCHAR(length=64), nullable=True))
    op.drop_column("users", "letterboxd_username")
    op.create_table(
        "wikifeet_models",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("model_name", sa.VARCHAR(), nullable=False),
        sa.Column("last_updated", sa.DATETIME(), nullable=False),
        sa.Column("foot_score", sa.FLOAT(), nullable=False),
        sa.Column("shoe_size", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "wikifeet_comments",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.INTEGER(), nullable=False),
        sa.Column("comment", sa.VARCHAR(length=512), nullable=False),
        sa.Column("user", sa.VARCHAR(length=64), nullable=False),
        sa.Column("user_title", sa.VARCHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["wikifeet_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment"),
    )
    op.create_table(
        "wikifeet_pictures",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.INTEGER(), nullable=False),
        sa.Column("picture_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["wikifeet_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("picture_id"),
    )
    # ### end Alembic commands ###
