"""Add User.letterboxd_user and WatchedMovie table

Revision ID: 98809285e64c
Revises: ff80cf34a64d
Create Date: 2025-09-11 12:45:58.486450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98809285e64c"
down_revision: Union[str, Sequence[str], None] = "ff80cf34a64d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikifeet_pictures")
    op.drop_table("wikifeet_models")
    op.drop_table("wikifeet_comments")
    op.add_column("movies_watched", sa.Column("film_year", sa.Integer(), nullable=False))
    op.add_column("movies_watched", sa.Column("user_rating", sa.Float(), nullable=False))
    op.add_column("movies_watched", sa.Column("watched_date", sa.DateTime(), nullable=False))
    op.drop_column("movies_watched", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies_watched", sa.Column("date", sa.DATETIME(), nullable=False))
    op.drop_column("movies_watched", "watched_date")
    op.drop_column("movies_watched", "user_rating")
    op.drop_column("movies_watched", "film_year")
    op.create_table(
        "wikifeet_comments",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.INTEGER(), nullable=False),
        sa.Column("comment", sa.VARCHAR(length=512), nullable=False),
        sa.Column("user", sa.VARCHAR(length=64), nullable=False),
        sa.Column("user_title", sa.VARCHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["wikifeet_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment"),
    )
    op.create_table(
        "wikifeet_models",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("model_name", sa.VARCHAR(), nullable=False),
        sa.Column("last_updated", sa.DATETIME(), nullable=False),
        sa.Column("foot_score", sa.FLOAT(), nullable=False),
        sa.Column("shoe_size", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "wikifeet_pictures",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.INTEGER(), nullable=False),
        sa.Column("picture_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["wikifeet_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("picture_id"),
    )
    # ### end Alembic commands ###
