"""add backloggd username and table

Revision ID: c0736c9f5911
Revises: 10572a9c2c1c
Create Date: 2025-11-20 16:32:46.870713

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0736c9f5911"
down_revision: Union[str, Sequence[str], None] = "10572a9c2c1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logged_games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("game_year", sa.Integer(), nullable=False),
        sa.Column("published_date", sa.DateTime(), nullable=False),
        sa.Column("user_rating", sa.Float(), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("poster_url", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("backloggd_username", sa.String(length=64), nullable=True))
    with op.batch_alter_table("users") as batch_op:
        batch_op.create_unique_constraint("backlogged_username", ["backloggd_username"])
        batch_op.create_unique_constraint("letterboxd_username", ["letterboxd_username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "backloggd_username")
    op.drop_table("logged_games")
    # ### end Alembic commands ###
