"""Fixing typo in columns of WatchedMovie table

Revision ID: ed64f2ad3f10
Revises: 2a2239fa06a2
Create Date: 2025-09-11 12:56:31.082572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed64f2ad3f10"
down_revision: Union[str, Sequence[str], None] = "2a2239fa06a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wikifeet_models")
    op.drop_table("wikifeet_comments")
    op.drop_table("wikifeet_pictures")
    op.add_column("movies_watched", sa.Column("tmdb_id", sa.Integer(), nullable=False))
    op.drop_column("movies_watched", "tmbd_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies_watched", sa.Column("tmbd_id", sa.INTEGER(), nullable=False))
    op.drop_column("movies_watched", "tmdb_id")
    op.create_table(
        "wikifeet_pictures",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.INTEGER(), nullable=False),
        sa.Column("picture_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["wikifeet_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("picture_id"),
    )
    op.create_table(
        "wikifeet_comments",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("model_id", sa.INTEGER(), nullable=False),
        sa.Column("comment", sa.VARCHAR(length=512), nullable=False),
        sa.Column("user", sa.VARCHAR(length=64), nullable=False),
        sa.Column("user_title", sa.VARCHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["wikifeet_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment"),
    )
    op.create_table(
        "wikifeet_models",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("model_name", sa.VARCHAR(), nullable=False),
        sa.Column("last_updated", sa.DATETIME(), nullable=False),
        sa.Column("foot_score", sa.FLOAT(), nullable=False),
        sa.Column("shoe_size", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
